version: '3'
# can extends service that you need
# remember you can use the same service name
# As backend service is not api service
services:

  api:
    extends:
      file: docker-compose-api.yml
      service: backend

  db:
    extends:
      file: docker-compose-database.yml
      service: database
