version: '3'
services:
  backend:
    container_name: nodejs
    build: .
    image: node
    ports:
      - '8000:8000'
    links: # to link containers over a network. When we link containers, Docker creates environment variables and adds containers to the known hosts list
      - database
    volumes:
      - information-database:/var/lib/mysql